name: Reusable Slack DM Notification

on:
  workflow_call:
    inputs:
      message_template:
        required: true
        type: string
      target_users:
        required: true
        type: string
      send_dm:
        required: false
        type: boolean
        default: true
    secrets:
      SLACK_BOT_TOKEN:
        required: true

jobs:
  notify_dm:
    runs-on: ubuntu-latest
    if: ${{ inputs.send_dm == 'true' && inputs.target_users != '' }}
    steps:
      - name: Send Slack DMs
        uses: actions/github-script@v7
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_REVIEWER_MAP: ${{ vars.SLACK_REVIEWER_MAP }}
        with:
          script: |
            // Get necessary parameters
            const [token, reviewerMap, targetUsers] = [
              process.env.SLACK_BOT_TOKEN,
              JSON.parse(process.env.SLACK_REVIEWER_MAP || "{}"),
              `${{ inputs.target_users }}`.split(',').map(u => u.trim()).filter(Boolean)
            ];

            // Find corresponding Slack user IDs
            const slackIds = [];
            targetUsers.forEach(user => {
              const id = reviewerMap[user] || reviewerMap[user?.toLowerCase()];
              if (id) slackIds.push(id);
            });

            const message = `${{ inputs.message_template }}`;
            const notifications = [];

            // Send DM to each Slack user ID
            slackIds.forEach(userId => {
              notifications.push(
                fetch('https://slack.com/api/chat.postMessage', {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                  body: JSON.stringify({ channel: userId, text: message })
                }).then(r => r.json()).then(r => core.info(r.ok ? `DM sent to ${userId}` : `DM failed: ${r.error}`))
              );
            });

            await Promise.allSettled(notifications);
            core.info(`Processed ${targetUsers.length} users → ${slackIds.length} Slack DMs`);
