name: Debug PR Review Trigger

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  echo-event:
    runs-on: ubuntu-latest
    steps:
      - name: Show review state & actor
        run: |
          echo "state=${{ github.event.review.state }}"
          echo "reviewer=${{ github.event.review.user.login }}"
          echo "pr=${{ github.event.pull_request.number }}"
          echo "from_fork=${{ github.event.pull_request.head.repo.fork }}"
      - name: Dump event JSON (first 5000 chars)
        run: |
          echo '${{ toJson(github.event) }}' | head -c 5000
